<?xml version="1.0" encoding="utf-8"?><Database Name="Rest_Hotel" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MEMO-HP;Initial Catalog=Rest_Hotel;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Rest_HotelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Carritoes" Member="Carritoes">
    <Type Name="Carritoe">
      <Column Name="Carrito_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Carrito_Restaurante" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Carrito_Tipo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Carrito_Nombre" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Carrito_Descripcion" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Carrito_Precio" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>