using System.ComponentModel.DataAnnotations;
using Hotel.Models;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rest_Hotel")]
	public partial class CarritoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public CarritoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Rest_HotelConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarritoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Carritoe> Carritoes
		{
			get
			{
				return this.GetTable<Carritoe>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Carritoes")]
	public partial class Carritoe
	{
		[Key]
		private System.Nullable<int> _Carrito_Id;
		
		private string _Carrito_Restaurante;
		
		private string _Carrito_Tipo;
		
		private string _Carrito_Nombre;
		
		private string _Carrito_Descripcion;
		
		private System.Nullable<decimal> _Carrito_Precio;
		
		public Carritoe()
		{
             
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrito_Id", DbType="Int",IsPrimaryKey = true)]
        [Key]
		public System.Nullable<int> Carrito_Id
		{
			get
			{
				return this._Carrito_Id;
			}
			set
			{
				if ((this._Carrito_Id != value))
				{
					this._Carrito_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrito_Restaurante", DbType="NVarChar(255)")]
		public string Carrito_Restaurante
		{
			get
			{
				return this._Carrito_Restaurante;
			}
			set
			{
				if ((this._Carrito_Restaurante != value))
				{
					this._Carrito_Restaurante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrito_Tipo", DbType="NVarChar(255)")]
		public string Carrito_Tipo
		{
			get
			{
				return this._Carrito_Tipo;
			}
			set
			{
				if ((this._Carrito_Tipo != value))
				{
					this._Carrito_Tipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrito_Nombre", DbType="NVarChar(255)")]
		public string Carrito_Nombre
		{
			get
			{
				return this._Carrito_Nombre;
			}
			set
			{
				if ((this._Carrito_Nombre != value))
				{
					this._Carrito_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrito_Descripcion", DbType="NVarChar(255)")]
		public string Carrito_Descripcion
		{
			get
			{
				return this._Carrito_Descripcion;
			}
			set
			{
				if ((this._Carrito_Descripcion != value))
				{
					this._Carrito_Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrito_Precio", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Carrito_Precio
		{
			get
			{
				return this._Carrito_Precio;
			}
			set
			{
				if ((this._Carrito_Precio != value))
				{
					this._Carrito_Precio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
